spring.application.name=Naengbuhae

# \uC8FC\uC18C
spring.datasource.url=jdbc:postgresql://db.lulvkjjxtmnvvqvnatbp.supabase.co:6543/postgres
# 6543\uC744 5432\uB85C \uC22B\uC790\uB9CC \uB531 \uBC14\uAFB8\uAE30!
#spring.datasource.url=jdbc:postgresql://db.lulvkjjxtmnvvqvnatbp.supabase.co:5432/postgres

# \uC544\uC774\uB514
spring.datasource.username=postgres

# \uBE44\uBC00\uBC88\uD638\uB294 \uD2BC\uD2BC\uD558\uAC8C \uC5F0\uACB0\uB41C \uAE08\uACE0(.env)\uC5D0\uC11C \uC548\uC804\uD558\uAC8C \uAEBC\uB0B4\uC624\uAE30!
spring.datasource.password=${DB_PASSWORD}

# \uC544\uB798 \uC124\uC815\uB4E4\uC740 \uADF8\uB300\uB85C \uC720\uC9C0
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true